services:
  postgres:
    container_name: cidadon_postgres
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cidadon
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: